# Software Name: its-client
# SPDX-FileCopyrightText: Copyright (c) 2016-2022 Orange
# SPDX-License-Identifier: MIT License
#
# This software is distributed under the MIT license, see LICENSE.txt file for more details.
#
# Author: Frédéric GARDES <frederic.gardes@orange.com> et al.
# Software description: This Intelligent Transportation Systems (ITS) [MQTT](https://mqtt.org/) client based on the [JSon](https://www.json.org) [ETSI](https://www.etsi.org/committee/its) specification transcription provides a ready to connect project for the mobility (connected and autonomous vehicles, road side units, vulnerable road users,...).
name: 'Docker run'
description: 'Build an image and run a container with the ITS client'
inputs:
  log_output: # log directory
    description: 'Log directory to use'
    required: true
    default: '/usr/src/app/log'
outputs:
  return_code: # return code of the binary
    description: 'The return code of the client'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --log-dir ${{ inputs.log_output }}
