name: Crates

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish the its library
        run: |
          cd rust/libits-client
          cargo publish --token ${{ secrets.CRATES_IO }}