name: Python its-client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          cd python/its-client
          python -m pip install --upgrade pip
          pip install coverage black wheel
          if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run black
        run: |
          cd python/its-client
          black --diff --check .
      - name: Run Unit Tests and generate coverage report
        run: |
          cd python/its-client
          python -m unittest -v
          coverage run -m unittest
          coverage report
          coverage html
      - name: Archive code coverage html report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: python/its-client/htmlcov
      - name: Run package creation
        run: |
          cd python/its-client
          python setup.py bdist_wheel
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: its_client
          path: python/its-client/dist
