name: Python its-quadkeys

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd python/its-quadkeys
          python -m pip install --upgrade pip
          pip install black wheel
      - name: Run black
        run: |
          cd python/its-quadkeys
          black --diff --check .
      - name: Run test-suite
        run: |
          cd python/its-quadkeys
          ./quadkeys-test
      - name: Run package creation
        run: |
          cd python/its-quadkeys
          python setup.py bdist_wheel
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: its_quadkeys
          path: python/its-quadkeys/dist
