name: Python its-interqueuemanager

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd python/its-interqueuemanager
          python -m pip install --upgrade pip
          pip install black wheel
      - name: Run black
        run: |
          cd python/its-interqueuemanager
          black --diff --check .
      - name: Run package creation
        run: |
          cd python/its-interqueuemanager
          python setup.py bdist_wheel
