name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run rustfmt
        run: |
          cd rust
          cargo fmt -- --check
      - name: Clippy
        run: |
          cd rust
          cargo clippy -- -D clippy::all

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build source
        run: |
          cd rust
          cargo build --verbose
      - name: Run tests
        run: |
          cd rust
          cargo test --verbose